// <auto-generated />
using System;
using CarApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221215101307_added-Dto")]
    partial class addedDto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarApi.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("SmartDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d581da4c-aa05-454c-b2f7-7be925c158d1"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("89c672e3-7e41-4efd-86e5-7a65a25d5b2e"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("47a17e97-c52f-4cc5-81c8-361149e0bf06"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("cfc7d438-8d3c-4a05-99db-b86c8976821a"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("f2e6b04b-32ee-4665-a4ef-23d7d06aa2b9"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("a09e9c2a-30a4-4eae-8ecd-d6cc9a4926e2"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("c6ae4fc6-aa53-42c5-860c-377860b8ed22"),
                            Brand = "John",
                            Color = "Somewhere",
                            FullDescription = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            SmartDescription = "",
                            State = "",
                            Year = 2008
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
