// <auto-generated />
using System;
using CarApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221215084137_first-migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d581da4c-aa05-454c-b2f7-7be925c158d1"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("b6a63561-5328-4211-81d6-41195057983e"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("2969ca26-53ee-43a5-b4d7-76f45b971d56"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("82c0294b-ddf8-4791-a121-f3d81f7af9c9"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("55ba7c75-765d-4881-bf55-605adcb500a3"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("658fcc45-373b-400d-8858-304c24f091ff"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("27bc80ab-2f07-4a6e-941d-58f6585c5723"),
                            Brand = "John",
                            Color = "Somewhere",
                            Description = "",
                            Model = "Iron Man",
                            Price = 2.02,
                            Year = 2008
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
