# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.9
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080